/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddApplicationRouteImport } from './routes/add-application'
import { Route as AiAnalyzerRouteImport } from './routes/ai-analyzer'
import { Route as ApplicationCopilotRouteImport } from './routes/application-copilot'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResumeAnalyzerRouteImport } from './routes/resume-analyzer'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as EditApplicationIdRouteImport } from './routes/edit-application.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddApplicationRoute = AddApplicationRouteImport.update({
  id: '/add-application',
  path: '/add-application',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAnalyzerRoute = AiAnalyzerRouteImport.update({
  id: '/ai-analyzer',
  path: '/ai-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationCopilotRoute = ApplicationCopilotRouteImport.update({
  id: '/application-copilot',
  path: '/application-copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeAnalyzerRoute = ResumeAnalyzerRouteImport.update({
  id: '/resume-analyzer',
  path: '/resume-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const EditApplicationIdRoute = EditApplicationIdRouteImport.update({
  id: '/edit-application/$id',
  path: '/edit-application/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-application': typeof AddApplicationRoute
  '/ai-analyzer': typeof AiAnalyzerRoute
  '/application-copilot': typeof ApplicationCopilotRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/resume-analyzer': typeof ResumeAnalyzerRoute
  '/signup': typeof SignupRoute
  '/edit-application/$id': typeof EditApplicationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-application': typeof AddApplicationRoute
  '/ai-analyzer': typeof AiAnalyzerRoute
  '/application-copilot': typeof ApplicationCopilotRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/resume-analyzer': typeof ResumeAnalyzerRoute
  '/signup': typeof SignupRoute
  '/edit-application/$id': typeof EditApplicationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-application': typeof AddApplicationRoute
  '/ai-analyzer': typeof AiAnalyzerRoute
  '/application-copilot': typeof ApplicationCopilotRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/resume-analyzer': typeof ResumeAnalyzerRoute
  '/signup': typeof SignupRoute
  '/edit-application/$id': typeof EditApplicationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-application'
    | '/ai-analyzer'
    | '/application-copilot'
    | '/dashboard'
    | '/login'
    | '/resume-analyzer'
    | '/signup'
    | '/edit-application/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-application'
    | '/ai-analyzer'
    | '/application-copilot'
    | '/dashboard'
    | '/login'
    | '/resume-analyzer'
    | '/signup'
    | '/edit-application/$id'
  id:
    | '__root__'
    | '/'
    | '/add-application'
    | '/ai-analyzer'
    | '/application-copilot'
    | '/dashboard'
    | '/login'
    | '/resume-analyzer'
    | '/signup'
    | '/edit-application/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddApplicationRoute: typeof AddApplicationRoute
  AiAnalyzerRoute: typeof AiAnalyzerRoute
  ApplicationCopilotRoute: typeof ApplicationCopilotRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ResumeAnalyzerRoute: typeof ResumeAnalyzerRoute
  SignupRoute: typeof SignupRoute
  EditApplicationIdRoute: typeof EditApplicationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-application': {
      id: '/add-application'
      path: '/add-application'
      fullPath: '/add-application'
      preLoaderRoute: typeof AddApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-analyzer': {
      id: '/ai-analyzer'
      path: '/ai-analyzer'
      fullPath: '/ai-analyzer'
      preLoaderRoute: typeof AiAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-copilot': {
      id: '/application-copilot'
      path: '/application-copilot'
      fullPath: '/application-copilot'
      preLoaderRoute: typeof ApplicationCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-analyzer': {
      id: '/resume-analyzer'
      path: '/resume-analyzer'
      fullPath: '/resume-analyzer'
      preLoaderRoute: typeof ResumeAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-application/$id': {
      id: '/edit-application/$id'
      path: '/edit-application/$id'
      fullPath: '/edit-application/$id'
      preLoaderRoute: typeof EditApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddApplicationRoute: AddApplicationRoute,
  AiAnalyzerRoute: AiAnalyzerRoute,
  ApplicationCopilotRoute: ApplicationCopilotRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ResumeAnalyzerRoute: ResumeAnalyzerRoute,
  SignupRoute: SignupRoute,
  EditApplicationIdRoute: EditApplicationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
